apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline_manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/idan-codefresh/pipeline_manager.git
    targetRevision: HEAD
  destination:
    name: nastasiia-martyniuk-codefresh-io-nastasiia-codefresh-us-east
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
